# -*- coding: utf-8 -*-
"""
Created on Thu Apr  9 11:32:23 2020

@author: sznik
"""
#to do

#write instructions: done
#offer to define the word
#only allow certain amount of inputs done

from random_word import RandomWords

counter = 0

def split(w):
    return list(w)

def letterpos(wrd, l):
    y = [i for i, d in enumerate(wrd) if d==l]
    x = [z + 1 for z in y]
    return x

r = RandomWords()
word = r.get_random_word()
word = word.lower()
lword = split(word)

print(lword)
print("Instructions:\nThis is a simple hangman game, you will receive a random word generated by python, and you have to submit your guessd letters and your final guess. They migh contain special characters as well. Everything is in lower case and you only have as many guesses as you have characters. Good Luck! :)")
print("Your word is", len(lword), "characters long")
letter = input("Enter your guess - ")

while len(letter) != len(lword):
    
    if len(letter) != len(lword):
        counter = counter + 1
        if letter in lword:
            indices = letterpos(lword, letter)
            print("The place of your letter(s) is/are:", indices)
            print("This is your", counter, "guess out of", len(lword))
                #print(lword.index(letter) + 1)
        if letter not in lword:
            print("Not in your word")
            print("This is your", counter, "guess out of", len(lword))
        if (counter ) == len(lword):
            print("GAME OVER")
            break
    letter = input("Enter your guess - ")
    if len(letter) == len(word):
        if split(letter) == lword:
            print("RIGHT")
            break
        else:
            print("GAME OVER")
    
#print(counter)